---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: b2-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.backblaze.com
  resources:
  - applicationkeys
  - b2accounts
  - buckets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.backblaze.com
  resources:
  - applicationkeys/finalizers
  - b2accounts/finalizers
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - b2.backblaze.com
  resources:
  - applicationkeys/status
  - b2accounts/status
  - buckets/status
  - clusterproviderconfigs/status
  - remoteclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - b2.backblaze.com
  resources:
  - b2accesspolicies
  - clusterproviderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.backblaze.com
  resources:
  - remoteclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
