#!/usr/bin/env bash
# Copies the rules controller-gen generates from +kubebuilder:rbac markers
# (config/rbac/role.yaml) into the Helm chart, so the chart's permissions
# never drift from the code. Run via `make manifests`.
set -euo pipefail
cd "$(dirname "$0")/.."

src=config/rbac/role.yaml
dst=charts/b2-operator/templates/clusterrole-manager.yaml

{
  echo "# Code generated by hack/sync-chart-rbac.sh from ${src}. DO NOT EDIT."
  echo "apiVersion: rbac.authorization.k8s.io/v1"
  echo "kind: ClusterRole"
  echo "metadata:"
  echo "  name: {{ include \"b2-operator.fullname\" . }}-manager"
  echo "  labels:"
  echo "    {{- include \"b2-operator.labels\" . | nindent 4 }}"
  sed -n '/^rules:/,$p' "${src}"
  cat <<'RULES'
# Required by the authenticated metrics endpoint.
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
RULES
} > "${dst}"
