//go:build !ignore_autogenerated

/*
Copyright 2026 Backblaze, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountAccess) DeepCopyInto(out *AccountAccess) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.Buckets.DeepCopyInto(&out.Buckets)
	in.Keys.DeepCopyInto(&out.Keys)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountAccess.
func (in *AccountAccess) DeepCopy() *AccountAccess {
	if in == nil {
		return nil
	}
	out := new(AccountAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountSecretReference) DeepCopyInto(out *AccountSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountSecretReference.
func (in *AccountSecretReference) DeepCopy() *AccountSecretReference {
	if in == nil {
		return nil
	}
	out := new(AccountSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationKey) DeepCopyInto(out *ApplicationKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationKey.
func (in *ApplicationKey) DeepCopy() *ApplicationKey {
	if in == nil {
		return nil
	}
	out := new(ApplicationKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationKeyList) DeepCopyInto(out *ApplicationKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationKeyList.
func (in *ApplicationKeyList) DeepCopy() *ApplicationKeyList {
	if in == nil {
		return nil
	}
	out := new(ApplicationKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationKeySpec) DeepCopyInto(out *ApplicationKeySpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.BucketRef != nil {
		in, out := &in.BucketRef, &out.BucketRef
		*out = new(LocalBucketReference)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]Capability, len(*in))
		copy(*out, *in)
	}
	if in.ValidFor != nil {
		in, out := &in.ValidFor, &out.ValidFor
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(KeyRotation)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretTemplate != nil {
		in, out := &in.SecretTemplate, &out.SecretTemplate
		*out = new(SecretTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.DeliverTo != nil {
		in, out := &in.DeliverTo, &out.DeliverTo
		*out = new(DeliveryTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationKeySpec.
func (in *ApplicationKeySpec) DeepCopy() *ApplicationKeySpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationKeyStatus) DeepCopyInto(out *ApplicationKeyStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.ScheduledRevocation != nil {
		in, out := &in.ScheduledRevocation, &out.ScheduledRevocation
		*out = (*in).DeepCopy()
	}
	if in.RetiringKeys != nil {
		in, out := &in.RetiringKeys, &out.RetiringKeys
		*out = make([]RetiringKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationKeyStatus.
func (in *ApplicationKeyStatus) DeepCopy() *ApplicationKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccessPolicy) DeepCopyInto(out *B2AccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccessPolicy.
func (in *B2AccessPolicy) DeepCopy() *B2AccessPolicy {
	if in == nil {
		return nil
	}
	out := new(B2AccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *B2AccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccessPolicyList) DeepCopyInto(out *B2AccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]B2AccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccessPolicyList.
func (in *B2AccessPolicyList) DeepCopy() *B2AccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(B2AccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *B2AccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccessPolicySpec) DeepCopyInto(out *B2AccessPolicySpec) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.ProviderConfigs != nil {
		in, out := &in.ProviderConfigs, &out.ProviderConfigs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Buckets.DeepCopyInto(&out.Buckets)
	in.Keys.DeepCopyInto(&out.Keys)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccessPolicySpec.
func (in *B2AccessPolicySpec) DeepCopy() *B2AccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(B2AccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2Account) DeepCopyInto(out *B2Account) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2Account.
func (in *B2Account) DeepCopy() *B2Account {
	if in == nil {
		return nil
	}
	out := new(B2Account)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *B2Account) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccountList) DeepCopyInto(out *B2AccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]B2Account, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccountList.
func (in *B2AccountList) DeepCopy() *B2AccountList {
	if in == nil {
		return nil
	}
	out := new(B2AccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *B2AccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccountSpec) DeepCopyInto(out *B2AccountSpec) {
	*out = *in
	out.PartnerConfigRef = in.PartnerConfigRef
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = new(AccountAccess)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccountSpec.
func (in *B2AccountSpec) DeepCopy() *B2AccountSpec {
	if in == nil {
		return nil
	}
	out := new(B2AccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2AccountStatus) DeepCopyInto(out *B2AccountStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2AccountStatus.
func (in *B2AccountStatus) DeepCopy() *B2AccountStatus {
	if in == nil {
		return nil
	}
	out := new(B2AccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bucket) DeepCopyInto(out *Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bucket.
func (in *Bucket) DeepCopy() *Bucket {
	if in == nil {
		return nil
	}
	out := new(Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketList) DeepCopyInto(out *BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketList.
func (in *BucketList) DeepCopy() *BucketList {
	if in == nil {
		return nil
	}
	out := new(BucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketPolicy) DeepCopyInto(out *BucketPolicy) {
	*out = *in
	if in.NamePatterns != nil {
		in, out := &in.NamePatterns, &out.NamePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketPolicy.
func (in *BucketPolicy) DeepCopy() *BucketPolicy {
	if in == nil {
		return nil
	}
	out := new(BucketPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketSpec) DeepCopyInto(out *BucketSpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.BucketInfo != nil {
		in, out := &in.BucketInfo, &out.BucketInfo
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LifecycleRules != nil {
		in, out := &in.LifecycleRules, &out.LifecycleRules
		*out = make([]LifecycleRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CORSRules != nil {
		in, out := &in.CORSRules, &out.CORSRules
		*out = make([]CORSRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultEncryption != nil {
		in, out := &in.DefaultEncryption, &out.DefaultEncryption
		*out = new(DefaultEncryption)
		**out = **in
	}
	if in.ObjectLock != nil {
		in, out := &in.ObjectLock, &out.ObjectLock
		*out = new(ObjectLock)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = make([]ReplicationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketSpec.
func (in *BucketSpec) DeepCopy() *BucketSpec {
	if in == nil {
		return nil
	}
	out := new(BucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketStatus) DeepCopyInto(out *BucketStatus) {
	*out = *in
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketStatus.
func (in *BucketStatus) DeepCopy() *BucketStatus {
	if in == nil {
		return nil
	}
	out := new(BucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORSRule) DeepCopyInto(out *CORSRule) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOperations != nil {
		in, out := &in.AllowedOperations, &out.AllowedOperations
		*out = make([]CORSOperation, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExposeHeaders != nil {
		in, out := &in.ExposeHeaders, &out.ExposeHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORSRule.
func (in *CORSRule) DeepCopy() *CORSRule {
	if in == nil {
		return nil
	}
	out := new(CORSRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfig) DeepCopyInto(out *ClusterProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfig.
func (in *ClusterProviderConfig) DeepCopy() *ClusterProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfigList) DeepCopyInto(out *ClusterProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfigList.
func (in *ClusterProviderConfigList) DeepCopy() *ClusterProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfigSpec) DeepCopyInto(out *ClusterProviderConfigSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.Partner != nil {
		in, out := &in.Partner, &out.Partner
		*out = new(PartnerSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfigSpec.
func (in *ClusterProviderConfigSpec) DeepCopy() *ClusterProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfigStatus) DeepCopyInto(out *ClusterProviderConfigStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyExpiresAt != nil {
		in, out := &in.KeyExpiresAt, &out.KeyExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastAuthorizedTime != nil {
		in, out := &in.LastAuthorizedTime, &out.LastAuthorizedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfigStatus.
func (in *ClusterProviderConfigStatus) DeepCopy() *ClusterProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretReference) DeepCopyInto(out *CredentialsSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretReference.
func (in *CredentialsSecretReference) DeepCopy() *CredentialsSecretReference {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultEncryption) DeepCopyInto(out *DefaultEncryption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultEncryption.
func (in *DefaultEncryption) DeepCopy() *DefaultEncryption {
	if in == nil {
		return nil
	}
	out := new(DefaultEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultRetention) DeepCopyInto(out *DefaultRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultRetention.
func (in *DefaultRetention) DeepCopy() *DefaultRetention {
	if in == nil {
		return nil
	}
	out := new(DefaultRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryTarget) DeepCopyInto(out *DeliveryTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryTarget.
func (in *DeliveryTarget) DeepCopy() *DeliveryTarget {
	if in == nil {
		return nil
	}
	out := new(DeliveryTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryTargetPattern) DeepCopyInto(out *DeliveryTargetPattern) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryTargetPattern.
func (in *DeliveryTargetPattern) DeepCopy() *DeliveryTargetPattern {
	if in == nil {
		return nil
	}
	out := new(DeliveryTargetPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyPolicy) DeepCopyInto(out *KeyPolicy) {
	*out = *in
	if in.AllowedCapabilities != nil {
		in, out := &in.AllowedCapabilities, &out.AllowedCapabilities
		*out = make([]Capability, len(*in))
		copy(*out, *in)
	}
	if in.MaxValidity != nil {
		in, out := &in.MaxValidity, &out.MaxValidity
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowedDeliveryTargets != nil {
		in, out := &in.AllowedDeliveryTargets, &out.AllowedDeliveryTargets
		*out = make([]DeliveryTargetPattern, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyPolicy.
func (in *KeyPolicy) DeepCopy() *KeyPolicy {
	if in == nil {
		return nil
	}
	out := new(KeyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRotation) DeepCopyInto(out *KeyRotation) {
	*out = *in
	if in.Every != nil {
		in, out := &in.Every, &out.Every
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRotation.
func (in *KeyRotation) DeepCopy() *KeyRotation {
	if in == nil {
		return nil
	}
	out := new(KeyRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSecretReference) DeepCopyInto(out *KubeconfigSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSecretReference.
func (in *KubeconfigSecretReference) DeepCopy() *KubeconfigSecretReference {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleRule) DeepCopyInto(out *LifecycleRule) {
	*out = *in
	if in.DaysFromUploadingToHiding != nil {
		in, out := &in.DaysFromUploadingToHiding, &out.DaysFromUploadingToHiding
		*out = new(int32)
		**out = **in
	}
	if in.DaysFromHidingToDeleting != nil {
		in, out := &in.DaysFromHidingToDeleting, &out.DaysFromHidingToDeleting
		*out = new(int32)
		**out = **in
	}
	if in.DaysFromStartingToCancelingUnfinishedLargeFiles != nil {
		in, out := &in.DaysFromStartingToCancelingUnfinishedLargeFiles, &out.DaysFromStartingToCancelingUnfinishedLargeFiles
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleRule.
func (in *LifecycleRule) DeepCopy() *LifecycleRule {
	if in == nil {
		return nil
	}
	out := new(LifecycleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalBucketReference) DeepCopyInto(out *LocalBucketReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalBucketReference.
func (in *LocalBucketReference) DeepCopy() *LocalBucketReference {
	if in == nil {
		return nil
	}
	out := new(LocalBucketReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectLock) DeepCopyInto(out *ObjectLock) {
	*out = *in
	if in.DefaultRetention != nil {
		in, out := &in.DefaultRetention, &out.DefaultRetention
		*out = new(DefaultRetention)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectLock.
func (in *ObjectLock) DeepCopy() *ObjectLock {
	if in == nil {
		return nil
	}
	out := new(ObjectLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartnerSettings) DeepCopyInto(out *PartnerSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartnerSettings.
func (in *PartnerSettings) DeepCopy() *PartnerSettings {
	if in == nil {
		return nil
	}
	out := new(PartnerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigReference) DeepCopyInto(out *ProviderConfigReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigReference.
func (in *ProviderConfigReference) DeepCopy() *ProviderConfigReference {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCluster) DeepCopyInto(out *RemoteCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCluster.
func (in *RemoteCluster) DeepCopy() *RemoteCluster {
	if in == nil {
		return nil
	}
	out := new(RemoteCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterList) DeepCopyInto(out *RemoteClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterList.
func (in *RemoteClusterList) DeepCopy() *RemoteClusterList {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterSpec) DeepCopyInto(out *RemoteClusterSpec) {
	*out = *in
	out.KubeconfigSecretRef = in.KubeconfigSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterSpec.
func (in *RemoteClusterSpec) DeepCopy() *RemoteClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterStatus) DeepCopyInto(out *RemoteClusterStatus) {
	*out = *in
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterStatus.
func (in *RemoteClusterStatus) DeepCopy() *RemoteClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationDestinationStatus) DeepCopyInto(out *ReplicationDestinationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationDestinationStatus.
func (in *ReplicationDestinationStatus) DeepCopy() *ReplicationDestinationStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationDestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationRule) DeepCopyInto(out *ReplicationRule) {
	*out = *in
	out.DestinationBucketRef = in.DestinationBucketRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationRule.
func (in *ReplicationRule) DeepCopy() *ReplicationRule {
	if in == nil {
		return nil
	}
	out := new(ReplicationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationStatus) DeepCopyInto(out *ReplicationStatus) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]ReplicationDestinationStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationStatus.
func (in *ReplicationStatus) DeepCopy() *ReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetiringKey) DeepCopyInto(out *RetiringKey) {
	*out = *in
	in.RevokeAfter.DeepCopyInto(&out.RevokeAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetiringKey.
func (in *RetiringKey) DeepCopy() *RetiringKey {
	if in == nil {
		return nil
	}
	out := new(RetiringKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretTemplate) DeepCopyInto(out *SecretTemplate) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretTemplate.
func (in *SecretTemplate) DeepCopy() *SecretTemplate {
	if in == nil {
		return nil
	}
	out := new(SecretTemplate)
	in.DeepCopyInto(out)
	return out
}
